#!/bin/bash

if [ ! -d "publish" ]; then
  echo "[info] publish 디렉토리가 존재하지 않습니다. 새로 생성합니다."
  mkdir publish
fi


bundlename=$1
if [ -z $bundlename ]; then
  bundlename="노씨데브_코드실행기"
fi

zippath="../publish/${bundlename}.zip"
cd dest
rm $(find . -type f -name ".DS_Store")
zip -q -r $zippath $(ls)

if [ $? -eq 0 ]; then
  echo "'publish/${bundlename}'가 성공적으로 생성되었습니다."
else
  echo "아카이빙 도중 문제가 발생했습니다."
fi



