#! /bin/bash

javac Solution.java

list=$(ls testcase)
for i in $list; do
  echo "-- test ${i} --"
  echo "출력"
  java -cp .nossi nossi.Main < "testcase/${i}/input.txt"
  echo "정답"
  cat "testcase/${i}/output.txt"
done

